import fs from "node:fs";
import path from "node:path";
import {
  BIOCITY_STANDS,
  briefingRoomLabel,
  CHALLENGE_COMPANIES,
  DEFAULT_TIME,
  EVENT_2026,
  getPlace3D,
  getStandPartner,
  getTarget3D,
  getTour3D,
  isPlaceId,
  legacyScene,
  normaliseTarget,
  PLACES_3D,
  placeForTarget,
  SHOWROOM_ORDER,
  showroomCounter,
  targetsForPlace,
  TARGETS_3D,
  TIME_PRESETS,
  TOURS_3D,
  TRANSFER_ROUTE,
  TWIN_CREDITS,
  VENUES,
  type PlaceId,
} from "@/lib/hackathon-2026";
import * as twin from "@/lib/hackathon-2026/twin";

/** routes.json is generated by scripts/twin/build-campus-data.mjs; the tours must match it. */
interface RoutesFile {
  walkSpeed: number;
  legs: Record<string, { lengthM: number; points: [number, number, number][] }>;
  tours: { id: string; legs: string[]; to: string; distanceM: number; minutes: number }[];
}
const routes = JSON.parse(
  fs.readFileSync(path.join(process.cwd(), "public/assets/guide/3d/data/routes.json"), "utf8"),
) as RoutesFile;

const PLACE_IDS: PlaceId[] = ["campus", "educity", "biocity", "joki"];
const unique = (xs: readonly string[]) => new Set(xs).size === xs.length;

/* ── Route geometry (campus frame: metres, +x east, +z south, so north is −z) ── */

const DEG = 180 / Math.PI;
/** Compass bearing (0 = north, 90 = east) of a ground direction. */
const bearing = (dx: number, dz: number) => ((Math.atan2(dx, -dz) * DEG) % 360 + 360) % 360;
/** Signed change of heading from bearing a to bearing b, −180…180: negative = a left turn. */
const headingChange = (a: number, b: number) => ((b - a + 540) % 360) - 180;

/** A tour's path from routes.json, with where each step's anchor lies along it (in walking order). */
function tourWalk(t: twin.Tour3D) {
  const path = t.legs.flatMap((id) => routes.legs[id].points.map(([x, , z]) => [x, z] as [number, number]));
  const cum = [0];
  for (let i = 1; i < path.length; i++)
    cum.push(cum[i - 1] + Math.hypot(path[i][0] - path[i - 1][0], path[i][1] - path[i - 1][1]));
  const total = cum[cum.length - 1];
  /** The point `s` metres along the path. */
  const at = (s: number): [number, number] => {
    const d = Math.max(0, Math.min(total, s));
    const i = Math.max(1, cum.findIndex((c) => c >= d));
    const u = (d - cum[i - 1]) / (cum[i] - cum[i - 1] || 1);
    return [path[i - 1][0] + u * (path[i][0] - path[i - 1][0]), path[i - 1][1] + u * (path[i][1] - path[i - 1][1])];
  };
  /** Heading of the straight line from s0 to s1 metres along — smooths out the router's sub-metre jogs. */
  const heading = (s0: number, s1: number) => {
    const [ax, az] = at(s0);
    const [bx, bz] = at(s1);
    return bearing(bx - ax, bz - az);
  };
  // Each anchor: the nearest point on the path at or after the previous step's.
  const anchors: { along: number; d: number }[] = [];
  let from = 0;
  for (const s of t.steps) {
    const [ax, az] = s.at ?? [Infinity, Infinity];
    let best = { d: Infinity, along: 0 };
    for (let i = 1; i < path.length; i++) {
      const [px, pz] = path[i - 1];
      const [qx, qz] = path[i];
      const l2 = (qx - px) ** 2 + (qz - pz) ** 2 || 1;
      const u = Math.max(0, Math.min(1, ((ax - px) * (qx - px) + (az - pz) * (qz - pz)) / l2));
      const along = cum[i - 1] + u * Math.sqrt(l2);
      if (along < from - 0.5) continue;
      const d = Math.hypot(ax - (px + u * (qx - px)), az - (pz + u * (qz - pz)));
      if (d < best.d - 1e-9) best = { d, along };
    }
    anchors.push(best);
    from = best.along;
  }
  return { total, at, heading, anchors };
}

/**
 * The turns of more than 45° between s0 and s1 metres along the path, in order: −1 = left,
 * +1 = right. Each 3 m stretch is compared with the heading before the turn.
 */
function turnsAlong(w: ReturnType<typeof tourWalk>, s0: number, s1: number): number[] {
  const turns: number[] = [];
  const end = Math.min(s1, w.total - 3);
  let ref = w.heading(s0, s0 + 3);
  for (let s = s0; s <= end; s += 0.5) {
    const change = headingChange(ref, w.heading(s, s + 3));
    if (Math.abs(change) > 45) {
      turns.push(Math.sign(change));
      s += 3; // past the corner
      ref = w.heading(s, s + 3);
    }
  }
  return turns;
}

describe("places", () => {
  it("are campus, EduCity, BioCity and Joki, each with a default view first", () => {
    expect(PLACES_3D.map((p) => p.id)).toEqual(PLACE_IDS);
    for (const p of PLACES_3D) {
      expect(p.views[0].id).toBe("default");
      expect(unique(p.views.map((v) => v.id))).toBe(true);
      expect(p.views.length).toBeGreaterThanOrEqual(4);
      for (const field of [p.tab, p.title, p.caption, p.alt, p.poster]) expect(field.trim()).not.toBe("");
      expect(p.poster).toMatch(/^\/assets\/guide\/3d\/.+\.webp$/);
      expect(getPlace3D(p.id)).toBe(p);
    }
  });

  it("offer the agreed views", () => {
    const views = Object.fromEntries(PLACES_3D.map((p) => [p.id, p.views.map((v) => `${v.id}:${v.label}`)]));
    expect(views).toEqual({
      campus: ["default:Overview", "arrival:Arrival · Tykistökatu", "courtyard:Jussin aukio", "top:Plan view"],
      educity: [
        "default:Lobby & Taidon portaat",
        "rooms1:Floor 1 rooms",
        "rooms2:Floor 2 rooms",
        "entrance:Main entrances",
      ],
      biocity: [
        "default:Build hall",
        "entrance:Partner entrance · Tykistökatu",
        "gallery:Aulagalleria",
        "stands:Partner stands",
      ],
      joki: ["default:Aula & Cave", "showroom:Showroom", "lounge:Company Lounge", "floors:Floors 2–3"],
    });
  });

  it("throw on an unknown place", () => {
    expect(() => getPlace3D("moon" as PlaceId)).toThrow("Unknown 3D place");
    expect(isPlaceId("joki")).toBe(true);
    expect(isPlaceId("lounge")).toBe(false);
    expect(isPlaceId(null)).toBe(false);
  });
});

describe("targets", () => {
  it("have unique ids, a place and readable text", () => {
    expect(unique(TARGETS_3D.map((t) => t.id))).toBe(true);
    for (const t of TARGETS_3D) {
      expect(PLACE_IDS).toContain(t.place);
      expect(t.label.trim()).not.toBe("");
      expect(t.detail.trim()).not.toBe("");
      if (t.href) expect(t.href).toMatch(/^\/hackathon-2026\/guide\//);
      expect(getTarget3D(t.id)).toBe(t);
      expect(placeForTarget(t.id)).toBe(t.place);
    }
  });

  it("give every company its Saturday Q&A stand in Joki", () => {
    for (const c of CHALLENGE_COMPANIES) {
      const t = getTarget3D(c.id)!;
      expect(t).toMatchObject({
        label: c.name,
        place: "joki",
        kind: "company",
        href: `/hackathon-2026/guide/challenge-partners/${c.id}`,
      });
      expect(t.detail).toContain(`Joki floor ${c.qa.floor}`);
    }
  });

  it("number the Showroom counters along the LED wall", () => {
    for (const id of SHOWROOM_ORDER) {
      const c = CHALLENGE_COMPANIES.find((x) => x.id === id)!;
      expect(getTarget3D(id)!.detail).toBe(
        `Joki floor 1 · Showroom · counter ${showroomCounter(c)} of ${SHOWROOM_ORDER.length}`,
      );
    }
    expect(getTarget3D("elisa")!.detail).toBe("Joki floor 1 · Showroom · counter 4 of 6");
  });

  it("give every company its Friday briefing room in EduCity", () => {
    for (const c of CHALLENGE_COMPANIES) {
      const t = getTarget3D(`room-${c.id}`)!;
      expect(t).toMatchObject({ place: "educity", kind: "room" });
      expect(t.detail).toContain(`EduCity floor ${c.briefing.floor} · Room ${briefingRoomLabel(c)}`);
      expect(t.detail).toContain("Fri 18:30–19:30");
    }
    expect(TARGETS_3D.filter((t) => t.kind === "room")).toHaveLength(CHALLENGE_COMPANIES.length);
  });

  it("include every BioCity stand with its partner from the stand plan", () => {
    for (const s of BIOCITY_STANDS) {
      const t = getTarget3D(s.id)!;
      expect(t).toMatchObject({ place: "biocity", kind: "stand" });
      const partner = getStandPartner(s);
      expect(t.label).toBe(partner ? `Stand ${s.rank} · ${partner.name}` : `Stand ${s.rank}`);
    }
    expect(getTarget3D("bc-1")!.label).toBe("Stand 1 · Red Hat");
    expect(getTarget3D("bc-2")!.label).toBe("Stand 2 · Solita");
  });

  it("include the entrances people actually use, with the corrected facts", () => {
    const e = (id: string) => getTarget3D(id)!;
    expect(e("entrance-biocity-tykistokatu")).toMatchObject({
      label: "BioCity main entrance",
      place: "biocity",
      kind: "entrance",
    });
    expect(e("entrance-biocity-tykistokatu").detail).toMatch(/companies and partners/);
    expect(e("entrance-biocity-courtyard").detail).toMatch(/Jussin aukio.*builders, from EduCity/);
    expect(e("entrance-educity-west").detail).toMatch(/deck level/);
    expect(e("entrance-educity-east").detail).toMatch(/deck level/);
    expect(e("entrance-joki-street").detail).toMatch(/Lemminkäisenkatu 12b · closed during the event/);
    for (const id of ["entrance-educity-b", "entrance-educity-gateway"]) expect(e(id).place).toBe("educity");
  });

  it("include the event areas and landmarks", () => {
    const ids = [
      "build-hall",
      "aula",
      "cave",
      "showroom",
      "lounge",
      "chill-zone",
      "taidon-portaat",
      "registration",
      "team-formation",
      "restaurant-kisalli",
      "serving-lines",
      "company-arrival",
      "jussin-aukio",
      "kupittaa-station",
      "parkcity",
      "supercars",
    ];
    for (const id of ids) expect(getTarget3D(id)).toBeDefined();
    expect(getTarget3D("supercars")!.label).toBe("Supercar display by Tykistökatu");
    expect(targetsForPlace("joki").map((t) => t.id)).toEqual(
      expect.arrayContaining(["aula", "cave", "lounge", "elisa"]),
    );
  });
});

describe("tours", () => {
  it("have unique ids, real steps and end at a known target in their place", () => {
    expect(unique(TOURS_3D.map((t) => t.id))).toBe(true);
    for (const t of TOURS_3D) {
      expect(getTarget3D(t.to)).toBeDefined();
      expect(t.place).toBe(placeForTarget(t.to));
      expect(t.steps.length).toBeGreaterThanOrEqual(3);
      for (const s of t.steps) expect(s.text).toMatch(/^[A-Z].*[.)]$/);
      expect(getTour3D(t.id)).toBe(t);
    }
  });

  it("use legs that exist in routes.json, connected end to end", () => {
    for (const t of TOURS_3D) {
      for (const id of t.legs) expect(routes.legs[id]).toBeDefined();
      for (let i = 1; i < t.legs.length; i++) {
        const a = routes.legs[t.legs[i - 1]].points.at(-1)!;
        const b = routes.legs[t.legs[i]].points[0];
        expect(Math.hypot(a[0] - b[0], a[2] - b[2])).toBeLessThan(0.6);
      }
    }
  });

  it("quote the measured distances and times (sum of the legs at 1.3 m/s)", () => {
    for (const t of TOURS_3D) {
      const sum = t.legs.reduce((n, id) => n + routes.legs[id].lengthM, 0);
      expect(Math.abs(t.distanceM - sum)).toBeLessThanOrEqual(1);
      expect(t.minutes).toBeCloseTo(t.distanceM / routes.walkSpeed / 60, 1);
    }
  });

  it("anchor every step on its route, in walking order", () => {
    for (const t of TOURS_3D) {
      for (const s of t.steps) expect(s.at).toBeDefined();
      const { anchors } = tourWalk(t);
      // Nearest point on the path at or after the previous step.
      for (const a of anchors) expect(a.d).toBeLessThan(3);
    }
  });

  it("number their steps uniquely (the 3D shows and announces the step a caption belongs to)", () => {
    for (const t of TOURS_3D) expect(unique(t.steps.map((s) => s.text))).toBe(true);
  });

  it("say left and right the way the route really turns", () => {
    // "<landmark> on your left/right": where the landmark stands ([x, z], LANDMARKS in engine/frame.ts).
    const SIDE_LANDMARKS: Record<string, [number, number]> = { "Joki tower": [58.9, 15.9] };
    const checked: string[] = [];
    for (const t of TOURS_3D) {
      const w = tourWalk(t);
      t.steps.forEach((step, i) => {
        const from = w.anchors[i].along;
        const until = i + 1 < t.steps.length ? w.anchors[i + 1].along : w.total;
        const turnWords: number[] = [];
        for (const clause of step.text.split(/[,;.—]/)) {
          for (const m of clause.matchAll(/\b(left|right)\b/gi)) {
            const side = m[1].toLowerCase() === "left" ? -1 : 1;
            const landmark = Object.keys(SIDE_LANDMARKS).find((name) => clause.includes(name));
            if (landmark && /\bon your (left|right)\b/i.test(clause)) {
              // A side: the landmark is on that side of the path where the step passes closest to it.
              const [lx, lz] = SIDE_LANDMARKS[landmark];
              let s = from;
              for (let x = from; x <= until; x += 0.5) {
                const [px, pz] = w.at(x);
                const [bx, bz] = w.at(s);
                if (Math.hypot(lx - px, lz - pz) < Math.hypot(lx - bx, lz - bz)) s = x;
              }
              const h = w.heading(Math.max(0, s - 1.5), Math.min(w.total, s + 1.5)) / DEG;
              const [dx, dz] = [Math.sin(h), -Math.cos(h)];
              const [px, pz] = w.at(s);
              // Right of the walking direction (dx, dz) is (−dz, dx) in this frame.
              const right = (lx - px) * -dz + (lz - pz) * dx;
              expect({ tour: t.id, step: i + 1, text: step.text, side: Math.sign(right) }).toEqual({
                tour: t.id,
                step: i + 1,
                text: step.text,
                side,
              });
            } else {
              turnWords.push(side);
            }
            checked.push(`${t.id}#${i + 1}`);
          }
        }
        if (!turnWords.length) return;
        // A turn: the first turns from the step's anchor on (from a little before it — corners are rounded,
        // so a turn can start a few metres before its anchor, never before the previous step's).
        const prev = i > 0 ? w.anchors[i - 1].along : 0;
        const turns = turnsAlong(w, Math.max(prev, from - 12), until + 3);
        expect({ tour: t.id, step: i + 1, text: step.text, turns: turns.slice(0, turnWords.length) }).toEqual({
          tour: t.id,
          step: i + 1,
          text: step.text,
          turns: turnWords,
        });
      });
    }
    // The check really ran: every left/right in the routes, including the ParkCity → BioCity start.
    expect(checked).toContain("companies-parkcity-to-biocity#1");
    expect(checked).toContain("builders-transfer-to-build#4");
    expect(checked.length).toBeGreaterThanOrEqual(12);
  });

  it("match the tours in routes.json", () => {
    expect(routes.tours.map((t) => t.id)).toEqual(TOURS_3D.map((t) => t.id));
    for (const t of TOURS_3D) {
      const r = routes.tours.find((x) => x.id === t.id)!;
      expect(r.legs).toEqual(t.legs);
      expect(r.to).toBe(t.to);
      expect(r.distanceM).toBe(t.distanceM);
      expect(r.minutes).toBe(t.minutes);
    }
  });

  it("cover the arrivals and moves of the weekend", () => {
    const to = (id: string) => getTour3D(id)!.to;
    expect(to("builders-train-checkin")).toBe("registration");
    expect(to("partners-fri-parkcity-edu")).toBe("company-arrival");
    expect(to("partners-fri-train-edu")).toBe("company-arrival");
    expect(to("partners-tykistokatu-to-stands")).toBe("bc-1");
    expect(to("builders-transfer-to-build")).toBe("build-hall");
    expect(to("companies-tykistokatu-to-showroom")).toBe("showroom");
    expect(to("builders-build-to-joki")).toBe("showroom");
    expect(to("builders-back-to-educity")).toBe("taidon-portaat");
    expect(TOURS_3D.length).toBe(12);
  });

  it("agree with the guide on the EduCity → BioCity transfer (about 200 m outdoors, 3 min)", () => {
    const xfer = getTour3D("builders-transfer-to-build")!;
    const outdoor = routes.legs[xfer.legs[0]].lengthM;
    expect(outdoor).toBeGreaterThan(190);
    expect(outdoor).toBeLessThan(220);
    expect(Math.round(outdoor / routes.walkSpeed / 60)).toBe(3);
    expect(TRANSFER_ROUTE.approxOutdoorDistance).toMatch(/200 m/);
    expect(getPlace3D("campus").caption).toMatch(/about 200 m/);
  });
});

describe("company routes", () => {
  const FRI = ["partners-fri-parkcity-edu", "partners-fri-train-edu", "partners-fri-stepfree-edu"];
  const SAT = ["companies-tykistokatu-to-showroom", "companies-train-to-biocity", "companies-parkcity-to-biocity"];
  const roomNumbers = (c: (typeof CHALLENGE_COMPANIES)[number]) => c.briefing.room.split(/\s*\/\s*/);

  it("name no single company's room in the routes everyone sees", () => {
    for (const t of TOURS_3D) {
      for (const text of [t.summary, ...t.steps.map((s) => s.text)]) expect(text).not.toMatch(/\broom \d{4}\b/);
    }
    for (const id of ["company-arrival", "entrance-educity-b"]) {
      expect(getTarget3D(id)!.label).not.toMatch(/\d{4}/);
      expect(getTarget3D(id)!.detail).not.toMatch(/\d{4}/);
    }
  });

  it("lead each company to its own Friday room and Saturday stand, keeping the steps' anchors", () => {
    for (const c of CHALLENGE_COMPANIES) {
      for (const id of [...FRI, ...SAT]) {
        const base = getTour3D(id)!;
        const t = twin.tourForCompany(base, c.id)!;
        expect(t.id).toBe(base.id);
        expect(t.steps.map((s) => s.at)).toEqual(base.steps.map((s) => s.at));
        expect(t.steps.slice(0, -1)).toEqual(base.steps.slice(0, -1));
        const text = `${t.summary} ${t.steps.at(-1)!.text}`;
        expect(t.steps.at(-1)!.text).toMatch(/^[A-Z].*[.)]$/);
        if (FRI.includes(id)) {
          expect(t.arrival).toBe(`room-${c.id}`);
          expect(text).toContain(`room ${briefingRoomLabel(c)}`);
          expect(text).toContain(`floor ${c.briefing.floor}`);
          for (const o of CHALLENGE_COMPANIES.filter((x) => x.briefing.room !== c.briefing.room))
            for (const n of roomNumbers(o)) expect(text).not.toContain(n);
        } else {
          expect(t.arrival).toBe(c.id);
          const counter = showroomCounter(c);
          expect(text).toContain(counter ? `counter ${counter} of ${SHOWROOM_ORDER.length}` : `floor ${c.qa.floor}`);
          // Saturday: the stand is ready — the Since AI team set it up from what the partner brought on Friday.
          expect(t.steps.at(-1)!.text).toMatch(/ready, set up by the Since AI team from the materials you brought on Friday/);
        }
      }
    }
  });

  it("leave other routes and unknown companies alone", () => {
    expect(twin.tourForCompany(getTour3D("builders-train-checkin")!, "elisa")).toBeNull();
    expect(twin.tourForCompany(getTour3D(FRI[0])!, "nope")).toBeNull();
    expect(twin.tourForCompany(getTour3D(FRI[0])!, null)).toBeNull();
  });

  it("give every step a short place name for the route card's now / next", () => {
    for (const t of TOURS_3D) for (const s of t.steps) expect(s.where?.trim()).toBeTruthy();
  });

  it("pair each company's Q&A stand with its Friday room and point at their floor plans", () => {
    for (const c of CHALLENGE_COMPANIES) {
      const stand = getTarget3D(c.id)!;
      const room = getTarget3D(`room-${c.id}`)!;
      expect(stand).toMatchObject({ company: c.id, day: "Sat", map: c.qa.floor === 1 ? "joki-showroom" : "joki-2-3" });
      expect(room).toMatchObject({ company: c.id, day: "Fri", map: c.briefing.floor === 1 ? "educity-1" : "educity-2" });
      expect(room.where).toBe(`EduCity · room ${c.briefing.room}`);
    }
    for (const t of TARGETS_3D) if (t.href?.includes("#map-")) expect(t.href).toBe(twin.mapHref(t.map!));
  });
});

describe("time presets", () => {
  it("are valid Turku wall-clock times during the event weekend", () => {
    expect(unique(TIME_PRESETS.map((p) => p.id))).toBe(true);
    const start = EVENT_2026.window.start.slice(0, 16);
    const end = EVENT_2026.window.end.slice(0, 16);
    for (const p of TIME_PRESETS) {
      expect(p.iso).toMatch(/^2026-11-0[6-8]T([01]\d|2[0-3]):[0-5]\d$/);
      const d = new Date(`${p.iso}:00Z`);
      expect(Number.isNaN(d.getTime())).toBe(false);
      expect(p.iso >= start && p.iso <= end).toBe(true);
      expect(p.label).toContain(p.iso.slice(11, 16));
    }
  });

  it("are the agreed moments, starting with Friday's arrival", () => {
    expect(TIME_PRESETS.map((p) => [p.id, p.iso])).toEqual([
      ["arrival", "2026-11-06T15:30"],
      ["sunset", "2026-11-06T16:20"],
      ["opening", "2026-11-06T17:00"],
      ["night", "2026-11-07T01:00"],
      ["qa", "2026-11-07T11:00"],
      ["closing", "2026-11-08T13:30"],
    ]);
    expect(DEFAULT_TIME).toBe("2026-11-06T15:30");
  });
});

describe("deep links", () => {
  it("normalise partners to their stands and ignore case", () => {
    expect(normaliseTarget("red-hat")).toBe("bc-1");
    expect(normaliseTarget("solita")).toBe("bc-2");
    expect(normaliseTarget("Red-Hat")).toBe("bc-1");
    expect(normaliseTarget(" ELISA ")).toBe("elisa");
    expect(normaliseTarget("BC-3")).toBe("bc-3");
  });

  it("map room numbers to the company's room and drop unknown ids", () => {
    expect(normaliseTarget("room-1002")).toBe("room-bayer");
    expect(normaliseTarget("room-2006")).toBe("room-valmet");
    expect(normaliseTarget("room-bayer")).toBe("room-bayer");
    expect(normaliseTarget("room-9999")).toBeNull();
    expect(normaliseTarget("nope")).toBeNull();
    expect(normaliseTarget("biocity")).toBeNull();
    expect(normaliseTarget("")).toBeNull();
    expect(normaliseTarget(null)).toBeNull();
    expect(normaliseTarget(undefined)).toBeNull();
  });

  it("place targets: companies in Joki, rooms in EduCity, stands in BioCity", () => {
    for (const c of CHALLENGE_COMPANIES) expect(placeForTarget(c.id)).toBe("joki");
    expect(placeForTarget("room-elisa")).toBe("educity");
    expect(placeForTarget("room-1001")).toBe("educity");
    expect(placeForTarget("bc-4")).toBe("biocity");
    expect(placeForTarget("red-hat")).toBe("biocity");
    expect(placeForTarget("solita")).toBe("biocity");
    expect(placeForTarget("entrance-joki-street")).toBe("joki");
    expect(placeForTarget("entrance-educity-something")).toBe("educity");
    expect(placeForTarget("lounge")).toBe("joki");
    expect(placeForTarget("registration")).toBe("educity");
    expect(placeForTarget("supercars")).toBe("biocity");
    expect(placeForTarget("jussin-aukio")).toBe("campus");
    expect(placeForTarget("joki")).toBe("joki");
    expect(placeForTarget("unknown")).toBe("campus");
    expect(placeForTarget(null)).toBe("campus");
  });

  it("understand the previous preview's ?scene= values", () => {
    expect(legacyScene("showroom")).toEqual({ place: "joki", view: "showroom" });
    expect(legacyScene("joki-tower")).toEqual({ place: "joki", view: "floors" });
    expect(legacyScene("biocity")).toEqual({ place: "biocity", view: "default" });
    expect(legacyScene("BioCity")).toEqual({ place: "biocity", view: "default" });
    expect(legacyScene("nope")).toBeNull();
    expect(legacyScene(null)).toBeNull();
    for (const ref of ["showroom", "joki-tower", "biocity"]) {
      const { place, view } = legacyScene(ref)!;
      expect(getPlace3D(place).views.map((v) => v.id)).toContain(view);
    }
  });

  it("export the twin's normaliseTarget from the package index", () => {
    expect(normaliseTarget).toBe(twin.normaliseTarget);
  });
});

describe("copy", () => {
  const corpus = JSON.stringify({ PLACES_3D, TARGETS_3D, TOURS_3D, TIME_PRESETS });

  it("uses the corrected venue facts (SPEC §10)", () => {
    expect(corpus).not.toMatch(/(?<!\d)50 m/); // the old "approx. 50 m outdoors" claim
    expect(corpus).not.toMatch(/first floor/i);
    expect(corpus).not.toMatch(/ground-floor main entrance/i);
    expect(corpus).toMatch(/Joki street door/);
    const joki = VENUES.find((v) => v.id === "joki")!;
    expect(joki.entrances.find((e) => e.label === "Street door")?.detail).toMatch(/closed during the event/);
  });

  it("names the companies and stands from the shared data", () => {
    for (const c of CHALLENGE_COMPANIES) expect(corpus).toContain(c.name);
    expect(getPlace3D("joki").alt).toContain("Meyer Turku, DNA, Apetit, Elisa, Turku Energia and Bayer");
    expect(getPlace3D("biocity").alt).toContain("Red Hat's stand (Stand 1)");
  });

  it("credits the open data", () => {
    expect(TWIN_CREDITS).toMatch(/© Turun kaupunki, CC BY 4\.0/);
    expect(TWIN_CREDITS).toMatch(/OpenStreetMap contributors/);
  });
});
