/**
 * three (and its addons) are ESM; this Jest setup runs CommonJS. The mocks hand over the real modules
 * through Node's own loader (as in massing.test.ts) — ground.ts is read only for its hero props.
 */
function nodeRequire(): NodeJS.Require {
  const mod = process.getBuiltinModule("module") as typeof import("module");
  return mod.createRequire(`${process.cwd()}/package.json`);
}
jest.mock("three", () => nodeRequire()(`${process.cwd()}/node_modules/three/build/three.module.js`));
jest.mock("three/addons/renderers/CSS2DRenderer.js", () => nodeRequire()("three/addons/renderers/CSS2DRenderer.js"));
jest.mock("three/addons/utils/BufferGeometryUtils.js", () => nodeRequire()("three/addons/utils/BufferGeometryUtils.js"));
jest.mock("three/addons/objects/Sky.js", () => nodeRequire()("three/addons/objects/Sky.js"));
jest.mock("three/addons/lights/SunLight.js", () => nodeRequire()("three/addons/lights/SunLight.js"));
jest.mock("three/addons/objects/Lensflare.js", () => nodeRequire()("three/addons/objects/Lensflare.js"));

import fs from "node:fs";
import path from "node:path";
import { PLAN_FRAMES, planToLocal } from "../../frame";
import type { V2 } from "../../types";
import { HERO_BOXES, HERO_PLANTERS } from "../../world/ground";
import type { Lod2Data, RoutesData } from "../campus";

/**
 * Route legs (routes.json, generated by scripts/twin/routes.mjs) never walk through a solid the scene
 * models along them: the terrace planters and drums, the small vent and stair boxes (LOD records under
 * 15 m²), the steps down from Joki's floor-2 door. Every outdoor leg is swept with a walker's body
 * (0.3 m radius) every 0.25 m.
 */
const ASSETS = path.join(process.cwd(), "public/assets/guide/3d");
const routes = JSON.parse(fs.readFileSync(path.join(ASSETS, "data/routes.json"), "utf8")) as RoutesData;
const lod2 = JSON.parse(fs.readFileSync(path.join(ASSETS, "data/lod2.json"), "utf8")) as Lod2Data;

const BODY = 0.3;

function pointInRing(p: V2, ring: readonly V2[]): boolean {
  let inside = false;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const [xi, zi] = ring[i];
    const [xj, zj] = ring[j];
    if (zi > p[1] !== zj > p[1] && p[0] < ((xj - xi) * (p[1] - zi)) / (zj - zi) + xi) inside = !inside;
  }
  return inside;
}
function distToRing(p: V2, ring: readonly V2[]): number {
  if (pointInRing(p, ring)) return -1;
  let best = Infinity;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const [ax, az] = ring[j];
    const ex = ring[i][0] - ax;
    const ez = ring[i][1] - az;
    const l2 = ex * ex + ez * ez || 1;
    const t = Math.max(0, Math.min(1, ((p[0] - ax) * ex + (p[1] - az) * ez) / l2));
    best = Math.min(best, Math.hypot(p[0] - ax - ex * t, p[1] - az - ez * t));
  }
  return best;
}
const ringArea = (r: readonly V2[]) => Math.abs(r.reduce((s, p, i) => s + p[0] * r[(i + 1) % r.length][1] - r[(i + 1) % r.length][0] * p[1], 0) / 2);

/** The solids: rings (planters, boxes) and round drums. */
const solids: { name: string; ring?: V2[]; c?: V2; r?: number }[] = [];
for (const p of HERO_PLANTERS) solids.push({ name: p.note, ring: p.ring });
for (const b of HERO_BOXES) {
  if (b.material === "dark" && b.note.includes("portal")) continue;
  if (typeof b.size === "number") solids.push({ name: b.note, c: b.center, r: b.size / 2 });
  else {
    const a = ((b.angle ?? 0) * Math.PI) / 180;
    const [w, d] = b.size;
    const ring = [
      [-w / 2, -d / 2],
      [w / 2, -d / 2],
      [w / 2, d / 2],
      [-w / 2, d / 2],
    ].map(([u, v]) => [b.center[0] + u * Math.cos(a) - v * Math.sin(a), b.center[1] + u * Math.sin(a) + v * Math.cos(a)] as V2);
    solids.push({ name: b.note, ring });
  }
}
for (const rec of lod2.buildings) {
  const ring = rec.footprint[0];
  if (ring && !rec.osmId && ringArea(ring) < 15 && rec.roofY - rec.groundY < 5) solids.push({ name: rec.id, ring });
}
// Joki's floor-2 north-east door steps: J frame, out along bearing 0.5° from r 9.25 to 11.45, 2.1 m wide.
{
  const b = (0.5 * Math.PI) / 180;
  const at = (r: number, s: number) => planToLocal(PLAN_FRAMES.J, Math.sin(b) * r + Math.cos(b) * s, -Math.cos(b) * r + Math.sin(b) * s);
  solids.push({ name: "Joki floor-2 door steps", ring: [at(9.25, -1.05), at(11.45, -1.05), at(11.45, 1.05), at(9.25, 1.05)] });
}

describe("route legs keep clear of the modelled solids", () => {
  it("has the solids to test against", () => {
    expect(solids.some((s) => s.name === "lod2-k50")).toBe(true);
    // The five planter drums on the event-entrance terrace (as rings or circles, wherever ground.ts keeps them).
    expect(solids.filter((s) => /drum/.test(s.name)).length).toBeGreaterThanOrEqual(5);
  });

  it("walks every outdoor leg without touching a planter, a drum, a vent box or the Joki steps", () => {
    const hits: string[] = [];
    for (const leg of Object.values(routes.legs)) {
      if (leg.mode !== "outdoor") continue;
      const pts = leg.points;
      // The leg to Joki's floor-2 door ends by climbing those steps (from their front).
      const climbs = (p: V2) => leg.id === "out-f-yard-tower" && Math.hypot(p[0] - 64.6, p[1] - 7.7) < 2.4;
      for (let i = 0; i + 1 < pts.length; i++) {
        const n = Math.max(1, Math.ceil(Math.hypot(pts[i + 1][0] - pts[i][0], pts[i + 1][2] - pts[i][2]) / 0.25));
        for (let k = 0; k <= n; k++) {
          const p: V2 = [pts[i][0] + ((pts[i + 1][0] - pts[i][0]) * k) / n, pts[i][2] + ((pts[i + 1][2] - pts[i][2]) * k) / n];
          for (const s of solids) {
            if (s.name.startsWith("Joki floor-2") && climbs(p)) continue;
            const d = s.ring ? distToRing(p, s.ring) : Math.hypot(p[0] - s.c![0], p[1] - s.c![1]) - s.r!;
            if (d < BODY) hits.push(`${leg.id} at (${p[0].toFixed(1)}, ${p[1].toFixed(1)}): ${s.name} (${d.toFixed(2)} m)`);
          }
        }
      }
    }
    expect([...new Set(hits.map((h) => h.split(" at ")[0] + " · " + h.split(": ")[1].split(" (")[0]))]).toEqual([]);
  });

  it("enters BioCity's event entrance through its outer doors, which face north-east", () => {
    const leg = routes.legs["out-xfer-edu-west-bio-event"].points;
    const [x1, , z1] = leg[leg.length - 1];
    // The last stretch arrives from the north-east, square to the doors (compass 55°).
    const before = leg.findLast((p) => Math.hypot(p[0] - x1, p[2] - z1) > 1.2)!;
    const door: V2 = [22.69, -8.01];
    const out = [Math.sin((55 * Math.PI) / 180), -Math.cos((55 * Math.PI) / 180)];
    const along = (before[0] - door[0]) * out[0] + (before[2] - door[1]) * out[1];
    expect(along).toBeGreaterThan(0.8);
  });
});
